require:
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop.disabled.yml

AllCops:
  EnabledByDefault: true

Metrics/ClassLength:
  CountComments: false
  Max: 150

Layout/LineLength:
 Max: 100
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoreCopDirectives: false
  IgnoredPatterns: []
  Exclude:
    - 'db/**/*.rb'
    - 'components/*/db/**/*.rb'
    - 'spec/features/*.rb'
    - 'components/*/spec/features/*.rb'
    - 'spec/controllers/*.rb'
    - 'components/*/spec/controllers/*.rb'